unovue/inspira-ui

components/content/common/CodeViewerTab.vue
components/content/common/ComponentViewer.vue
components/content/inspira/examples/marquee/ReviewCard.vue
content/2.components/marquee.md

Allow users to access the `ReviewCard` component which is used in the Marquee Demo.

docs: make ReviewCard available

---

components/content/inspira/examples/images-slider/ImagesSliderDemo.vue
components/content/inspira/ui/images-slider/ImagesSlider.vue
content/2.components/0.all.md
content/2.components/images-slider.md

Based on the [Aceternity Images Slider](https://ui.aceternity.com/components/images-slider) component and powered by Vue Transitions.
- **Horizontal & Vertical Animations**: You can animate the images horizontally (default) or vertically with the `direction` prop.
- **Preloaded Images**: Images are preloaded before showing, preventing flickering loading animation.
- **Customisable Autoplay**: Automatically transition through your slides, or allow your users to navigate manually.
- **Overlay Anything**: The default slot allows you to overlay whatever content you wish overlay slider.

feat: add ImagesSlider component

---

components/content/inspira/examples/DirectionAwareHoverDemo.vue
components/content/inspira/ui/direction-aware-hover/DirectionAwareHover.vue
content/2.components/0.all.md
content/2.components/direction-aware-hover.md

implementation of https://ui.aceternity.com/components/direction-aware-hover in nuxt

feat: direction aware hover component

---

components/content/inspira/examples/HyperTextDemo.vue
components/content/inspira/ui/hyper-text/HyperText.vue
content/2.components/0.all.md
content/2.components/hyper-text.md

Implementation of [Hyper Text Component](https://magicui.design/docs/components/hyper-text) by Magic UI

feat: add HyperText component

---

components/content/inspira/examples/TextRevealDemo.vue
components/content/inspira/ui/text-reveal-card/TextRevealCard.vue
components/content/inspira/ui/text-reveal-card/TextRevealStars.vue
content/2.components/0.all.md
content/2.components/text-reveal-card.md

implementation of https://ui.aceternity.com/components/text-reveal-card in nuxt

feat: text reveal card component

---

.prettierignore
.prettierrc.mjs
package.json
pnpm-lock.yaml

- Prettier with default config for consistent code formatting.

feat: add prettier

---

components/content/inspira/ui/pattern-background/PatternBackground.vue
components/content/inspira/ui/pattern-background/index.ts
content/2.components/pattern-background.md

Change Speed props to number (ms) + improve doc

PatternBackground  - Props + doc improvments

---

components/content/inspira/examples/BentoGridDemo2.vue
components/content/inspira/ui/bento-grid/BentoGrid.vue
components/content/inspira/ui/bento-grid/BentoGridCard.vue
components/content/inspira/ui/bento-grid/BentoGridItem.vue
content/2.components/bento-grid.md

- Add image example to BentoGridDemo2
- Refactor code to extract props as type

BentoGrid - Docs improvment and code consistency

---

components/content/inspira/examples/LinkPreviewDemo.vue
components/content/inspira/ui/link-preview/LinkPreview.vue
content/2.components/link-preview.md
package.json
pnpm-lock.yaml

implementation of https://ui.aceternity.com/components/link-preview in nuxt

feat: link preview component

---

components/content/inspira/examples/vortex/VortexDemo.vue
components/content/inspira/examples/vortex/VortexFullPageDemo.vue
components/content/inspira/ui/vortex/Vortex.vue
content/2.components/vortex.md
package.json

feat: add Vortex component

---

components/content/inspira/examples/VanishingInputDemo.vue
components/content/inspira/ui/vanishing-input/VanishingInput.vue
content/2.components/placeholders-and-vanish-input.md

implementation of https://ui.aceternity.com/components/placeholders-and-vanish-input in nuxt

feat: placeholders and vanish input component

---

eslint.config.js
nuxt.config.ts
package.json
pnpm-lock.yaml

Add Nuxt ESLint plugin
Fix .md file rule

Improve ESLint

---

components/content/inspira/examples/MultiStepLoaderDemo.vue
components/content/inspira/ui/multi-step-loader/MultiStepLoader.vue
content/2.components/multi-step-loader.md

implementation of https://ui.aceternity.com/components/multi-step-loader in nuxt with the ability to handle async loading conditions

feat: add multi-step-loader component

---

components/content/inspira/examples/sparkles/SparklesDemo.vue
components/content/inspira/examples/sparkles/SparklesFullPageDemo.vue
components/content/inspira/ui/sparkles/Sparkles.vue
content/2.components/sparkles.md

implementation of https://ui.aceternity.com/components/sparkles in nuxt

feat: sparkles component

---

components/content/inspira/examples/flip-card/FlipCardDemo.vue
components/content/inspira/examples/flip-card/FlipCardHorizontalDemo.vue
components/content/inspira/ui/flip-card/FlipCard.vue
content/2.components/flip-card.md

Add a dynamic flip card with smooth 180-degree flipping animations along both the X and Y axes, providing an engaging and interactive visual effect.

Feat: Add Flip Card component

---

components/content/inspira/examples/AnimatedTooltipDemo.vue
components/content/inspira/ui/animated-tooltip/AnimatedTooltip.vue
content/2.components/animated-tooltip.md

Implementation of https://ui.aceternity.com/components/animated-tooltip in nuxt

feat: animated-tooltip component

---

app.config.ts

|Before|After|
|:--:|:--:|
|![image](https://github.com/user-attachments/assets/fcd59364-a2b9-48d4-b206-5709de734cc2)| ![Screenshot From 2024-12-02 13-40-28](https://github.com/user-attachments/assets/ac875b2c-724e-4229-bd10-47692ecfd002)|

fix: carbon ad format

---

components/content/inspira/examples/flickering-grid/FlickeringGridDemo.vue
components/content/inspira/ui/flickering-grid/FlickeringGrid.vue
content/2.components/flickering-grid.md

This is a new component. Design From [magicui flickering-grid](https://magicui.design/docs/components/flickering-grid)
preview gif:

feat: flickering-grid component,forked from magicui

---

components/content/inspira/examples/scratch-to-reveal/ScratchToRevealDemo.vue
components/content/inspira/ui/scratch-to-reveal/ScratchToReveal.vue
content/2.components/scratch-to-reveal.md

This is a new component. Design From [MagicUI Scratch To Reveal](https://magicui.design/docs/components/scratch-to-reveal)
gif preview:

feat: Scratch To Reveal component, forked from MagicUI

---

components/content/inspira/examples/morphing-text/MorphingTextDemo.vue
components/content/inspira/ui/morphing-text/MorphingText.vue
content/2.components/morphing-text.md

This is a new component. Design From [Magic UI Morphing Text](https://magicui.design/docs/components/morphing-text)
[preview:
https://github.com/user-attachments/assets/105d1ec4-7fd9-494a-8b44-b4f12ebe29a6

feat: Morphing Text component, forked from Magic UI.

---

components/content/inspira/examples/interactive-hover-button/InteractiveHoverButtonDemo.vue
components/content/inspira/examples/interactive-hover-button/VeryLongTextInteractiveHoverButtonDemo.vue
components/content/inspira/ui/interactive-hover-button/InteractiveHoverButton.vue
content/2.components/interactive-hover-button.md

This component forked from [Magic UI Interactive Hover Button](https://magicui.design/docs/components/interactive-hover-button).
preview:
https://github.com/user-attachments/assets/a04e45e0-c3bf-478a-b57b-27eb00d668fa

feat: Interactive Hover Button component, forked from Magic UI

---

components/content/inspira/examples/tetris/TetrisDemo.vue
components/content/inspira/ui/tetris/Tetris.vue
content/2.components/tetris.md
package.json
pnpm-lock.yaml

Tetris Component, Inspired and ported from [Nuxt UI Home](https://ui.nuxt.com/).
Component preview:
https://github.com/user-attachments/assets/1ac89ead-6902-4289-ace7-508f2d12d623

feat: Tetris Component, forked from Nuxt UI Home page

---

components/content/inspira/examples/morphing-tabs/MorphingTabsDemo.vue
components/content/inspira/ui/morphing-tabs/MorphingTabs.vue
content/2.components/morphing-tabs.md

This is a morphing tabs interaction, recreated by Preet's work and featuring the gooey effect component.
Preview:
https://github.com/user-attachments/assets/fb064fa7-727e-4ab2-87cd-ac5291e25553

feat: Morphing Tabs component

---

components/content/inspira/examples/BookDemo.vue
components/content/inspira/ui/book/Book.vue
components/content/inspira/ui/book/BookDescription.vue
components/content/inspira/ui/book/BookHeader.vue
components/content/inspira/ui/book/BookTitle.vue
components/content/inspira/ui/book/index.ts
content/2.components/book.md

This is a new component. Design From [x/ui - 3D Book](https://ui.3x.gl/docs/book)
https://github.com/user-attachments/assets/de8f270d-31f3-4870-8a07-72ff98e43049

feat: 3DBook component, forked from x/ui

---

components/content/inspira/examples/warp-background/WarpBackgroundDemo.vue
components/content/inspira/ui/warp-background/Beam.vue
components/content/inspira/ui/warp-background/WarpBackground.vue
content/2.components/warp-background.md

Warp Background Component, forked from [Magic UI WarpBackground](https://magicui.design/docs/components/warp-background)
preview:
https://github.com/user-attachments/assets/4ada97d8-f2ab-4d59-80f7-75bb31e412b5

feat: Warp Background Component, forked from Magic UI.

---

components/content/inspira/examples/FileUploadDemo.vue
components/content/inspira/ui/file-upload/FileUpload.vue
components/content/inspira/ui/file-upload/FileUploadGrid.vue
content/2.components/file-upload.md

This is a new component. Design From [File Upload - AcernityUI](https://ui.aceternity.com/components/file-upload)
https://github.com/user-attachments/assets/07175a25-f4c4-486a-9330-368c6ec17fdd

feat: add File Upload component, forked from AcernityUI

---

components/content/inspira/examples/RippleButtonDemo.vue
components/content/inspira/ui/ripple-button/RippleButton.vue
content/2.components/ripple-button.md

This is a new component. Design From [Ripple Button - MagicUI](https://magicui.design/docs/components/ripple-button)
https://github.com/user-attachments/assets/e2e28766-66a9-483e-8cb4-db3ab9e0615c

feat: add RippleButton component, forked from MagicUI

---

components/content/inspira/examples/FileTreeDemo.vue
components/content/inspira/ui/file-tree/File.vue
components/content/inspira/ui/file-tree/Folder.vue
components/content/inspira/ui/file-tree/Tree.vue
components/content/inspira/ui/file-tree/TreeIndicator.vue
components/content/inspira/ui/file-tree/index.ts
content/2.components/file-tree.md

This is a new component. Design From [MagicUI](https://magicui.design/docs/components/file-tree)
https://github.com/user-attachments/assets/ce4a4c9f-27d3-46dd-be0e-8bd2c40846f0

feat: add FileTree component, forked from MagicUI

---

components/content/inspira/examples/IconCloudDemo.vue
components/content/inspira/ui/icon-cloud/IconCloud.vue
components/content/inspira/ui/icon-cloud/index.ts
content/2.components/icon-cloud.md

This is a new component. Design From [MagicUI](https://magicui.design/docs/components/icon-cloud)
https://github.com/user-attachments/assets/b5d0e716-83b6-4b99-820b-9080f88560e5

feat: add IconCloud component, forked from MagicUI

---

components/content/inspira/examples/AnimatedBeamDemo2.vue
components/content/inspira/examples/ContainerScrollDemo.vue
components/content/inspira/examples/GlowBorderDemo.vue
components/content/inspira/examples/TextGenerateDemo.vue
components/content/inspira/examples/TextHoverEffectDemo.vue
components/content/inspira/examples/TextScrollRevealDemo.vue
components/content/inspira/examples/flickering-grid/FlickeringGridDemo.vue
components/content/inspira/examples/glare-card/GlareCardDemo.vue
components/content/inspira/examples/pattern-background/PatternBackgroundBigDotDemo.vue
components/content/inspira/examples/pattern-background/PatternBackgroundDotDemo.vue
components/content/inspira/examples/pattern-background/PatternBackgroundGridDemo.vue
components/content/inspira/examples/pattern-background/PatternBackgroundGridSmallDemo.vue
components/content/inspira/examples/text-generate-effect/TextGenerateEffectDemoDelayed.vue

Found a couple more now everything is converted!

fix: convert className attributes to class in vue component examples

---

components/content/inspira/examples/interactive-grid-pattern/InteractiveGridPatternColoredDemo.vue
components/content/inspira/examples/interactive-grid-pattern/InteractiveGridPatternDemo.vue
components/content/inspira/ui/interactive-grid-pattern/InteractiveGridPattern.vue
content/2.components/interactive-grid-pattern.md

This is a new component. Design From [MagicUI](https://magicui.design/docs/components/interactive-grid-pattern)
https://github.com/user-attachments/assets/ea7013f1-a879-4e39-83da-d9733ed7c32a

feat: add InteractiveGridPattern component, forked from MagicUI

---

components/content/inspira/examples/AnimatedListDemo.vue
components/content/inspira/ui/animated-list/AnimatedList.vue

fix: add loop animation for the AnimatedList.vue

---

components/content/inspira/examples/line-shadow-text/LineShadowTextDemo.vue
components/content/inspira/ui/line-shadow-text/LineShadowText.vue
content/2.components/line-shadow-text.md

Poretd from [Magic UI's Line Shadow Text Component](https://magicui.design/docs/components/line-shadow-text)

Add Line Shadow Text Component

---

components/content/inspira/examples/colourful-text/ColourfulTextDemo.vue
components/content/inspira/ui/colourful-text/ColourfulText.vue
content/2.components/text-animations/colorful-text.md

Component forked from [Aceternity UI Colourful Text](https://ui.aceternity.com/components/colourful-text)
preview: 
https://github.com/user-attachments/assets/dc650e1d-bdc0-4a45-8eb8-02eaa048ca17

feat: Colourful Text Component forked from Aceternity UI

---

components/content/inspira/examples/true-focus/TrueFocusDemo.vue
components/content/inspira/examples/true-focus/TrueFocusManualModeDemo.vue
components/content/inspira/ui/true-focus/TrueFocus.vue
content/2.components/miscellaneous/true-focus.md

Inspired by [reactbits](https://www.reactbits.dev/text-animations/true-focus).
It's a ClientOnly component.
Preview:
https://github.com/user-attachments/assets/a0e17ff2-e6b3-45ec-acd7-df822a95b251

feat: TrueFocus component from reactbits

---

components/content/inspira/examples/DockDemo2.vue
components/content/inspira/ui/dock/Dock.vue
components/content/inspira/ui/dock/DockIcon.vue
components/content/inspira/ui/dock/DockSeparator.vue
components/content/inspira/ui/dock/index.ts
components/content/inspira/ui/dock/injectionKeys.ts
components/content/inspira/ui/dock/types.ts
content/1.getting-started/2.installation.md
content/2.components/miscellaneous/Dock.md

Add a vertically arranged Dock component and modify the documentation

Add Vertical Dock

---

README.md
README_CN.md

In order to make it easier for developers from China to read this document, I have independently made a Simplified Chinese translation of README.md.
There are 2 updates at here:
1. doc: New README_CN.md
adds a new version of README.md, translated into chinese.
2. doc: Update README.md
adds a link to the chinese version of README.md

doc: Simplified Chinese version README_CN.md Uploaded

---

components/content/inspira/ui/timeline/Timeline.vue

Fix z-index issue in sticky section of Timeline component (close #157)

---

components/content/inspira/examples/flip-card/FlipCardDemo.vue
components/content/inspira/examples/flip-card/FlipCardHorizontalDemo.vue
components/content/inspira/ui/flip-card/FlipCard.vue
content/2.components/cards/flip-card.md

Added slots on both sides of the card, allowing users to decide their own display content.

refactor(FlipCard): Make FlipCard component usage scenarios more general

---

components/content/inspira/ui/colourful-text/ColourfulText.vue

Try to fix the bug of `Uncaught TypeError: Cannot read properties of null (reading '0')` (#162 )
Use visibilityState and v-if to control the components
Only have one thing doesn't works very will is will trigger and replay the animation when back to the tab with <ColourfulText />

fix: fixed the bug of `Cannot read properties of null` in ColorfulText

---

components/content/inspira/examples/container-text-flip/ContainerTextFlipDemo.vue
components/content/inspira/examples/container-text-flip/ContainerTextFlipHeroDemo.vue
components/content/inspira/examples/container-text-flip/ContainerTextFlipStandardDemo.vue
components/content/inspira/ui/container-text-flip/ContainerTextFlip.vue
components/content/inspira/ui/container-text-flip/index.ts
content/2.components/text-animations/container-text-flip.md

This component ported from [Aceternity UI Container Text Flip](https://ui.aceternity.com/components/container-text-flip).

feat: container-text-flip component ported from aceternity ui

---

components/content/inspira/examples/smooth-cursor/SmoothCursorDemo.vue
components/content/inspira/ui/smooth-cursor/DefaultCursor.vue
components/content/inspira/ui/smooth-cursor/SmoothCursor.vue
components/content/inspira/ui/smooth-cursor/index.ts
content/2.components/miscellaneous/smooth-cursor.md

This component ported from ported from [Magic UI Smooth Cursor](https://magicui.design/docs/components/smooth-cursor)

feat: smooth-cursor component ported from magic ui

---

content/2.components/buttons/interactive-hover-button.md

docs: Remove redundant id to fix code preview bug

---

components/content/inspira/examples/aurora-background/AuroraBackgroundDemo.vue
components/content/inspira/examples/colourful-text/ColourfulTextDemo.vue
components/content/inspira/ui/blur-reveal/BlurReveal.vue
components/content/inspira/ui/box-reveal/BoxReveal.vue

refactor: use whileInView instead of inView

---

components/content/inspira/ui/colourful-text/ColourfulText.vue

Fix colorful text rendering

---

components/content/inspira/examples/color-picker/ColorPickerDemo.vue
components/content/inspira/ui/color-picker/ColorPicker.vue
components/content/inspira/ui/color-picker/ContrastRatio.vue
components/content/inspira/ui/color-picker/ObjectColorInput.vue
components/content/inspira/ui/color-picker/index.ts
content/2.components/input-and-forms/color-picker.md
package.json
pnpm-lock.yaml
scripts/crawl-content.ts

- Multiple color formats (HEX, HSL, HSLA, RGB, RGBA with alpha channel)
- Interactive saturation, hue, and alpha sliders
- Alpha channel support with transparency slider for RGBA/HSLA modes
- Custom color swatches with default predefined colors
- Accessibility contrast checker with AA/AAA indicators

feat: add Color Picker component
