- components/content/inspira/ui/animated-list/AnimatedList.vue
This pull request is intended to do two things namely:
1. Fix the type error that occurs when the `initial` and `enter` directives are set to `null` instead of `undefined`. It throws this error: `Type 'null' is not assignable to type 'Variant | undefined'.`
2. Fix the list overlapping over the other list as it is animating in, this pull request intends to fix that by changing:
- The transition property from `ease-in-out` to `ease-out`.
- The `stiffness` from `350` to `250`.
-  The `originY` property to `y`.
> fix: list overlap

- components/content/inspira/ui/logo-origami/LogoOrigami.vue
TransitionGroup does not take 'mode' prop
```ts
export type TransitionGroupProps = Omit<TransitionProps, 'mode'> & {
tag?: string;
moveClass?: string;
};
```
> fix: remove TransitionGroup unavailable prop mode

- content/1.getting-started/3.contribution.md
Add a section about props inside the contribution guide, it's a suggestion to standardize the way component are defined.
> Contribution guide improvment

- components/content/common/HomePageExamples.vue
**What was wrong?**
Examples were overflowing their container on the frontpage
**What was the fix?**
I've added overflow hidden on the example's container
> fix(homepage examples): Fixed corners overflowing rounded borders

- components/content/inspira/examples/ripple/RippleDemo.vue
- components/content/inspira/examples/ripple/RippleDemoBlobed.vue
- components/content/inspira/examples/ripple/RippleDemoLinesOnly.vue
- components/content/inspira/examples/ripple/RippleDemoSquared.vue
- components/content/inspira/ui/ripple/Ripple.vue
- components/content/inspira/ui/ripple/RippleCircle.vue
- components/content/inspira/ui/ripple/RippleContainer.vue
- content/2.components/lens.md
- content/2.components/ripple.md
- tailwind.config.ts
- Remove inline CSS styles
- Add `props` to configure behavior
- Add `RippleContainer` for lazy developers
- Move classes to props in order to make them configurable
- Remove useless `<div>`
- Convert `second` to `ms`
> Improve and clean Ripple component

- components/content/common/toast/Toast.vue
- components/content/common/toast/ToastAction.vue
- components/content/common/toast/ToastClose.vue
- components/content/common/toast/ToastDescription.vue
- components/content/common/toast/ToastProvider.vue
- components/content/common/toast/ToastTitle.vue
- components/content/common/toast/ToastViewport.vue
- components/content/common/toast/Toaster.vue
- components/content/common/toast/index.ts
- components/content/common/toast/use-toast.ts
Added a dedicated toast component.
```vue
<template>
<Toaster />
<UiButton @click="toast({ description: 'hello' })">
toast
</UiButton>
</template>
<script setup lang="ts">
import { useToast } from '~/components/content/common/toast';
const config = useConfig();
const { toast } = useToast();
</script>
```
> feat: add toast component

- components/content/inspira/ui/morphing-text/MorphingText.vue
Changed the `class` attribute of the SVG element with ID `filters` from `hidden size-full` to `fixed size-0`.
As a result, the Morphing animation now works as expected in Firefox.
Closing #87.
> fix: Morphing Text animation on Firefox

- components/content/inspira/examples/AnimatedTooltipDemo.vue
- components/content/inspira/examples/OrbitDemo.vue
- components/content/inspira/examples/OrbitDemoSynchronized.vue
- components/content/inspira/ui/animated-tooltip/AnimatedTooltip.vue
- components/content/inspira/ui/letter-pullup/LetterPullup.vue
- components/content/inspira/ui/sparkles-text/SparklesText.vue
- eslint.config.js
This PR introduces a new ESLint rule enforcing the block order for Vue components as specified in the project's style guide. The enforced order is:  
1. `<template>`  
2. `<script>`  
3. `<style>`  
All existing Vue files have been updated to comply with this rule.
> refactor: add ESLint rule for Vue block order

- components/content/inspira/examples/ScriptCopyDemo.vue
- components/content/inspira/ui/script-copy/ScriptCopy.vue
- content/2.components/script-copy.md
This is a new component. Design From [Script Copy Button - MagicUI](https://magicui.design/docs/components/script-copy-btn)
https://github.com/user-attachments/assets/886d3a3d-188d-4fce-a905-1bcef796c28f
> feat: add Script Copy component, forked from MagicUI

- components/content/inspira/ui/file-tree/index.ts
Basically fixed this error present now in the production build:
```
ReferenceError: Cannot access 'se' before initialization
at 4cZgqYbA.js:1:3139
```
> fix: add missing import for the file-tree components

- content/2.components/3d-card.md
- content/2.components/animated-beam.md
- content/2.components/animated-list.md
- content/2.components/blur-reveal.md
- content/2.components/border-beam.md
- content/2.components/file-upload.md
- content/2.components/flickering-grid.md
- content/2.components/glow-border.md
- content/2.components/meteors.md
- content/2.components/morphing-text.md
- content/2.components/tetris.md
- content/2.components/text-generate-effect.md
- content/2.components/text-hover-effect.md
- content/2.components/text-scroll-reveal.md
Improved docs after [Discussion 99](https://github.com/unovue/inspira-ui/discussions/99)
> docs: add warning alerts for Nuxt-only syntax in component documentation

- components/content/inspira/ui/logo-origami/LogoOrigami.vue
LogoOrigami component in browser, animation is break.Maybe dont't use TransitionGroup?
before:
https://github.com/user-attachments/assets/5ec35224-3481-4e4e-b9fc-01a8ffc98f54
after: 
https://github.com/user-attachments/assets/5136992e-5b44-4eb7-b5e3-3ad52f7028aa
> fix(LogoOrigami.vue): maybe don't use TransitionGroup?

- content/1.getting-started/2.installation.md
Fix the content attribute in the tailwind.config.js config file
Problem: The content attribute in the [doc](https://inspira-ui.com/getting-started/installation#update-tailwindconfigjs-and-tailwindcss) is empty, it will cause error during installation
> docs: fix content attribute in tailwind.config.js

- content/1.getting-started/2.installation.md
optimized the content in tailwind.config.js config file.
Obviously, there is an extra comma in this part of the code below, which may be a minor error, but on some older versions it will cause browsers to fail to understand it.
> docs: optimized the content in tailwind.config.js config file.

- components/content/inspira/examples/AnimatedBeamDemo.vue
- components/content/inspira/ui/animated-beam/AnimatedBeam.vue
The original plan was to compare the positions of the `fromRef` and `toRef` elements on the page, and the final execution direction of the beam animation could be from `fromRef` to `toRef`, or from `toRef` to `fromRef`, which is very uncontrollable because the positions of `fromRef` and `toRef` may change due to responsive layouts.
The modified plan is that the beam animation will always be from `fromRef` to `toRef`, which is also more in line with the semantics of these 2 `props`.
> fix(AnimatedBeam): fix the direction of beam animation execution

- content/1.getting-started/2.installation.md
Change explanation:
Fixed spelling error: Changed "depedencies" → "dependencies" in the section heading to correct the misspelling of the word referring to required software packages.
> docs:Update 2.installation.md

- components/content/common/InstallationCli.vue
For Bun, `dlx` is not supported. Use `bunx` or `bun x` instead.
Reference: https://bun.sh/docs/cli/bunx
> Fix bun CLI

- components/content/inspira/ui/number-ticker/NumberTicker.vue
Added a new watch on `props.value` to update `transitionValue`, ensuring the value transitions correctly when the element has been in view and continues reactivity after initial load.
Test by changing 100 into any other number on `<NumberTicker :value="100" />`.
> fix(NumberTicker): Add reacting to prop.value changes

- components/content/common/CodeViewerTab.vue
> fix(CodeViewerTab): adjust positioning of CodeCopy component

- components/content/inspira/examples/scroll-island/ScrollIslandDemo.vue
Now, after the component at the top of the ScrollIsland page is clicked, the anchor link cannot jump normally. The reason is that the original href of the a tag is incorrectly written. Users may feel confused when browsing the web. Now this problem has been fixed. Users can jump normally in documents, which enhances the usability of the documents. 
**Code changes:**
before:
after:
**Documentation changes:**
before:
https://github.com/user-attachments/assets/8788cbd7-4434-4e9f-8b5e-aa2dd2ac49c4
after:
https://github.com/user-attachments/assets/cab1f8fa-3404-473f-a4f6-6a4bb7cba19e
> docs(ScrollIslandDemo): Modify the a tag in ScrollIsland to make it jump to the anchor point normally, and enhance document availability

- components/content/inspira/ui/glow-border/GlowBorder.vue
**Problem description:**
When using interactive components such as <input /> inside the <slot /> of the Glow Border component, event penetration does not work.
**Solution:**
Add the pointer-events-none attribute to the inner elements of the Glow Border component.
> style(GlowBorder): Increase mouse event passthrough

- .vscode/settings.json
- components/content/inspira/ui/logo-origami/LogoOrigami.vue
Because the zindex of the two static parts is not small enough, flickering occurs. Now I fixed it.
View comparison:
Before:
https://github.com/user-attachments/assets/d037cc64-85b9-4135-836c-04317be89532
After:
https://github.com/user-attachments/assets/308ae2eb-47d0-4719-b5f7-45626064b39f
> fix(LogoOrigami): Fixed the flickering phenomenon of LogoOrigami when flipping

- components/content/inspira/ui/lens/Lens.vue
In latest version of Vue/Nuxt, `props.hovering` is automatically defaults to `false` instead of `undefined`, which means it won't work without needing the user to pass in their own `hovering` ref, this adjustment makes sure it should be defaults to `undefined` and allow it to work with `localIsHovering`
> fix: allow Lens to works without `hovering` ref
